spring:
  liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.xml

  application:
    name: name-jdbc
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    password: 0095
    url: jdbc:p6spy:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        types:
          print:
            warn :false
    show-sql: true
sentry:
  dsn: https://e21d5808d8b53f1bea05d737e50cf20d@o4508398301872128.ingest.de.sentry.io/4508398307704912
  environment: "development"
  traces-sample-rate: 1.0    # 1.0 - barcha requestlarni kuzatadi
  debug: false                # Debug rejimini yoqing (faqat test uchun)'

server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: "none"
#  api-docs:
#    path: /v3/docs
